# Generated by Django 4.0.2 on 2023-06-13 00:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projectinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectinfo',
            unique_together={('username', 'projectname')},
        ),
    ]
